### ISSUE TITLE
enhancement: hide icon

### ISSUE THREAD

**Issue by Erik262** [JoniVR/MonitorControl#4]
Hi, what about hiding the icon on the top bar?
Im using other tools, which have exactly the same icon.

by the way 
very nice work!
only your project is working on my computer :)

**Comment by JoniVR** [comment]
Sure, but how would a user access their preferences if the icon is hidden? 
Any suggestions on this? 

_I'm currently a bit busy so this might take some time before I can get to it._

**Comment by Erik262** [comment]
Yes, What about putting it in the system preferences next to java? or by double-clicking on the program?

**Comment by JoniVR** [comment]
> putting it in the system preferences next to java

I'm afraid that would require a rewrite of the preferences panel, the current implementation doesn't allow us to simply add it as a button in the system preferences afaik. 

This tool uses a framework to manage the preferences pane [MASPreferences](https://github.com/shpakovski/MASPreferences), so doing what you're suggesting would require switching to a different framework or implementing it manually entirely.

I also think it would make the user experience more confusing, because not a lot of apps use the system preferences to display their preferences.

> double-clicking on the program

What do you mean by this? Opening the program again? I think that would be a bit confusing too, it's different if you have an app that has an actual window, but for a menulet like this it just doesn't make sense to me. 

You can, however, use [Vanilla](https://matthewpalmer.net/vanilla/) (free) or [Bartender](https://www.macbartender.com/) to hide the icons you don't want to see. I'm personally using bartender through my [SetApp](https://setapp.com/) subscription. But that's up to you of course 😉

**edit:** 
I'm considering this closed, if you really want it implemented I'd suggest submitting a Pull Request for it.
